### ISSUE TITLE
Sent using PodMail.

### ISSUE THREAD

**Issue by Slivo-fr** [zKillboard/podmail#5]
Title.

Any chance to make this optional ?
Not that I don't want to promote the tool (I already started :D) but I hate having junk automatically added to my mails

Thanks !

**Comment by cvweiss** [comment]
For now I'll leave it. Maybe in the future I'll be greedy and make it a paid option to remove it. (Something really cheap, like 1m ISK/month)

**Comment by Slivo-fr** [comment]
😢 

any idea on when we could pay for this ?

**Comment by cvweiss** [comment]
> Maybe in the future
