### ISSUE TITLE
Moved mail still shows in inbox?

### ISSUE THREAD

**Issue by jaqdaw** [zKillboard/podmail#7]
If I move a mail in-game to a folder for archiving or whatever, the mail still shows on Podmail in the inbox. I can't see any way to move mail in POdmail. The only way to get it out of the inbox is to delete it. Otherwise these mails seem to persist indefinitely.

**Comment by cvweiss** [comment]
The game doesn't always reflect folder locations properly into ESI. Also, if ESI reflects the change it may take some time for podmail to detect the change, especially when there are many evemails to iterate.

**Comment by jaqdaw** [comment]
Ok thanks
